services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Webconsulting\Agentation\:
    resource: '../Classes/*'

  Webconsulting\Agentation\Controller\Backend\ModuleController:
    public: true

  Webconsulting\Agentation\Controller\Backend\ApiProxyController:
    public: true

  Webconsulting\Agentation\AdminPanel\AgentationModule:
    public: true
